### ISSUE TITLE
"cannot execute binary file" error

### ISSUE THREAD

**Issue by casey** [peaceiris/actions-mdbook#321]
I'm getting the following error when when trying to run an actions-mdbook installed mdbook binary:

```
/Users/runner/work/_temp/bfe5655f-fa0a-410b-9608-62a44511a89b.sh: line 2: /Users/runner/toolbin/mdbook: cannot execute binary file
```

Here's a [link](https://github.com/casey/intermodal/pull/474/checks?check_run_id=1088410223#step:17:9) to the GitHub actions run.

It looks like the last previous successful run was two days ago. Might something have changed between now and then that's causing this error?

**Comment by casey** [comment]
I downgraded `mdbook-version` from `latest` to `0.4.2`, so I think this is an issue with mdbook v0.4.3. However, it's such a curious error. I can't imagine how a change to mdbook could result in an unexecutable binary. It could be something weird with github actions caching on my end.

**Comment by peaceiris** [comment]
Thank you for reporting this!

I opened https://github.com/rust-lang/mdBook/issues/1318

And, this action failed to catch the error. I will fix this.

**Comment by casey** [comment]
Thank you for digging in to the error! I should have checked the latest mdbook release assets.

**Comment by peaceiris** [comment]
https://github.com/rust-lang/mdBook/issues/1318 has been closed. mdBook v0.4.3 works well on macOS now.

Log: https://github.com/peaceiris/actions-mdbook/pull/322/checks?check_run_id=1094152485

**Comment by casey** [comment]
Awesome, everything works on my end: https://github.com/casey/intermodal/actions/runs/248755166
