### ISSUE TITLE
proposal: update to Node.js 20

### ISSUE THREAD

**Issue by RadxaYuntian** [peaceiris/actions-mdbook#503]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Currently the following warning will be generated when using this action:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-mdbook@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### Describe the solution you'd like

Update to Node.js 20.

### Describe alternatives you've considered

Use something else.

### Additional context

Biannual occurrence: #465

**Comment by peaceiris** [comment]
fixed by https://github.com/peaceiris/actions-mdbook/pull/500
